# Locate hax Shared library
#
# This module defines:
#  HAX_FOUND, if false, do not try to link to hax
#  HAX_LIBRARIES
#  HAX_INCLUDE_DIRS, where to find Hax/Hax.hpp

SET( CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR} ${CMAKE_MODULE_PATH} )
SET(Boost_USE_MULTITHREAD ON)

FIND_PACKAGE(Boost 1.46 COMPONENTS filesystem thread system date_time REQUIRED)
FIND_PACKAGE(log4cpp REQUIRED)
FIND_PACKAGE(Lua51 REQUIRED)
FIND_PACKAGE(OGRE REQUIRED)
FIND_PACKAGE(OIS REQUIRED)
FIND_PACKAGE(CEGUI REQUIRED)
FIND_PACKAGE(toluapp REQUIRED)
FIND_PACKAGE(ParticleUniverse REQUIRED)
FIND_PACKAGE(YAJL REQUIRED)
FIND_PACKAGE(CURL REQUIRED)

SET(HAX_PATHS
  /usr
  /usr/local
  ../Hax
  /home/kandie/Workspace/Projects/Hax
)

FIND_PATH(HAX_INCLUDE_DIRS Hax/Hax.hpp
  HINTS
  PATH_SUFFIXES include
  PATHS
  ${HAX_PATHS}
)

FIND_LIBRARY(HAX_LIBRARIES
  NAMES Hax
  HINTS
  PATH_SUFFIXES lib
  PATHS
  ${HAX_PATHS}
)

IF(HAX_LIBRARIES AND HAX_INCLUDE_DIRS)
  SET( HAX_INCLUDE_DIRS 
    ${HAX_INCLUDE_DIRS}
    ${Boost_INCLUDE_DIRS}
    ${LOG4CPP_INCLUDE_DIR}
    ${LUA_INCLUDE_DIR}
    ${TOLUAPP_INCLUDE_DIR}
    ${OGRE_INCLUDE_DIRS}
    ${OIS_INCLUDE_DIRS}
    ${CEGUI_INCLUDE_DIR}
    ${ParticleUniverse_INCLUDE_DIRS}
    ${YAJL_INCLUDE_DIR}
    ${CURL_INCLUDE_DIR}
    )
  
  SET( HAX_LIBRARIES
    ${HAX_LIBRARIES}
    ${Boost_LIBRARIES}
    ${OGRE_LIBRARIES}
    ${CEGUI_LIBRARY}
    ${CEGUILuaScriptModule_LIBRARY}
    ${CEGUIOgre_LIBRARY}
    ${LUA_LIBRARIES}
    ${TOLUAPP_LIBRARIES}
    ${OIS_LIBRARIES}
    ${LOG4CPP_LIBRARIES}
    ${ParticleUniverse_LIBRARY}
    ${YAJL_LIBRARY}
    ${CURL_LIBRARY}
    pthread)
  
  SET( HAX_FOUND TRUE )
  MESSAGE(STATUS "Found Hax!")
ELSE()
  MESSAGE(STATUS "Error! Could not find Hax!")
ENDIF()

MARK_AS_ADVANCED(HAX_FOUND)
